# This rule is not used by the project memgraph-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to memgraph.base14.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: memgraph-operator
    app.kubernetes.io/managed-by: kustomize
  name: memgraphcluster-viewer-role
rules:
- apiGroups:
  - memgraph.base14.io
  resources:
  - memgraphclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - memgraph.base14.io
  resources:
  - memgraphclusters/status
  verbs:
  - get
